# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
  module Bakelite
    module Docs
      module B_ARCHITECTURE
        # # Chunking and Streaming IO
        #
        # Bakelite achieves constant O(chunk_size) memory usage during file reading by
        # partitioning large files into discrete, individually compressed chunks and
        # streaming them on demand using Bakelite::FileIO.
        #
        # ### Executive Summary & Key Topics
        #
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Topic</th>
        #       <th>Method / Anchor</th>
        #       <th>Description</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td><strong>Partitioning and Compression</strong></td>
        #       <td><code>.topic_01_chunking_mechanism</code></td>
        #       <td>How files are split and verified.</td>
        #     </tr>
        #     <tr>
        #       <td><strong>Bakelite::FileIO Semantics</strong></td>
        #       <td><code>.topic_02_streaming_file_io</code></td>
        #       <td>Transparent seeking and reading through standard Crystal IO.</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        module CHUNKING_AND_IO
          # **Partitioning and Compression**: How files are split and verified.
          #
          # When a file is stored using `store`, Bakelite's `Chunker` divides the raw stream
          # into fixed segments (default 64KB). Each chunk contains:
          # - 64-bit absolute file offset
          # - 32-bit compressed length
          # - 32-bit uncompressed length
          # - 32-bit CRC32 checksum
          # - Compressed byte payload (Deflate, Gzip, Zlib, or raw)
          #
          # During verification (`bakelite verify`), each chunk's CRC32 checksum is checked
          # against the decompressed bytes, ensuring bit-perfect integrity.
          #
          def self.topic_01_chunking_mechanism : Nil; end

          # **Bakelite::FileIO Semantics**: Transparent seeking and reading through standard Crystal IO.
          #
          # `Bakelite::FileIO` inherits directly from `IO`, enabling it to be passed into
          # standard Crystal parsers (JSON.parse, YAML.parse, image loaders, XML parsers).
          #
          # Key IO operations:
          # - `read(slice)`: Reads arbitrary byte lengths across multiple chunk boundaries.
          # - `seek(offset, whence)`: Supports `IO::Seek::Set`, `IO::Seek::Current`, and `IO::Seek::End`.
          # - Active chunk caching: Only decompresses a chunk when the read pointer lands inside it, caching the active chunk for sequential reads.
          #
          def self.topic_02_streaming_file_io : Nil; end
        end
      end
    end
  end
{% end %}
