# ==============================================================================
# Bakelite::Docs Documentation System - Master Index & Navigation Hub
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# ==============================================================================

{% unless flag?(:release) %}
  module Bakelite
    # The `Bakelite::Docs` module is the authoritative technical reference and documentation guide.
    #
    # ## Learning Tracks & Topic Index
    #
    # The documentation is paced into 4 distinct tracks:
    #
    # ### 1. Overview (`A_OVERVIEW`)
    # <table>
    #   <thead>
    #     <tr>
    #       <th>Submodule</th>
    #       <th>Title</th>
    #       <th>Description</th>
    #     </tr>
    #   </thead>
    #   <tbody>
    #     <tr>
    #       <td><code>INTRODUCTION</code></td>
    #       <td><strong>Introduction to Bakelite</strong></td>
    #       <td>High-performance virtual filesystem and binary container engine for Crystal.</td>
    #     </tr>
    #   </tbody>
    # </table>
    #
    # ### 2. Architecture (`B_ARCHITECTURE`)
    # <table>
    #   <thead>
    #     <tr>
    #       <th>Submodule</th>
    #       <th>Title</th>
    #       <th>Description</th>
    #     </tr>
    #   </thead>
    #   <tbody>
    #     <tr>
    #       <td><code>CHUNKING_AND_IO</code></td>
    #       <td><strong>Chunking and Streaming IO</strong></td>
    #       <td>Architecture of bounded-memory streaming and random access IO.</td>
    #     </tr>
    #   </tbody>
    # </table>
    #
    # ### 3. Dsl (`C_DSL`)
    # <table>
    #   <thead>
    #     <tr>
    #       <th>Submodule</th>
    #       <th>Title</th>
    #       <th>Description</th>
    #     </tr>
    #   </thead>
    #   <tbody>
    #     <tr>
    #       <td><code>MACROS_AND_VOLUMES</code></td>
    #       <td><strong>Compile-Time DSL and Volumes</strong></td>
    #       <td>Using Bakelite macros to embed and organize assets in code.</td>
    #     </tr>
    #   </tbody>
    # </table>
    #
    # ### 4. Containers (`D_CONTAINERS`)
    # <table>
    #   <thead>
    #     <tr>
    #       <th>Submodule</th>
    #       <th>Title</th>
    #       <th>Description</th>
    #     </tr>
    #   </thead>
    #   <tbody>
    #     <tr>
    #       <td><code>BINARY_CONTAINERS</code></td>
    #       <td><strong>Binary Containers and CLI Toolchain</strong></td>
    #       <td>Post-compile executable overlay and standalone archive manipulation.</td>
    #     </tr>
    #   </tbody>
    # </table>
    #
    module Docs
      # **Quick-Start Commands**: Essential commands for building, running, and testing.
      #
      # #### Bakelite Quick Start:
      # ```bash
      # shards install
      # crystal spec
      # bin/bakelite pack bin/game.exe assets/ --mount assets
      # ```
      def self.topic_01_quick_start : Nil; end

      # **Learning Tracks & Reading Paths**: Curated reading order from beginner to advanced.
      #
      # #### Structured Learning Tracks
      #
      # ##### 1. Overview (`A_OVERVIEW`)
      # - `A_OVERVIEW::INTRODUCTION`: **Introduction to Bakelite** &mdash; High-performance virtual filesystem and binary container engine for Crystal.
      #
      # ##### 2. Architecture (`B_ARCHITECTURE`)
      # - `B_ARCHITECTURE::CHUNKING_AND_IO`: **Chunking and Streaming IO** &mdash; Architecture of bounded-memory streaming and random access IO.
      #
      # ##### 3. Dsl (`C_DSL`)
      # - `C_DSL::MACROS_AND_VOLUMES`: **Compile-Time DSL and Volumes** &mdash; Using Bakelite macros to embed and organize assets in code.
      #
      # ##### 4. Containers (`D_CONTAINERS`)
      # - `D_CONTAINERS::BINARY_CONTAINERS`: **Binary Containers and CLI Toolchain** &mdash; Post-compile executable overlay and standalone archive manipulation.
      #
      def self.topic_02_reading_paths : Nil; end

      # **Master Table of Contents**: Complete hierarchical topic index.
      #
      # #### Complete Documentation Index
      #
      # ##### `A_OVERVIEW`
      # - `A_OVERVIEW::INTRODUCTION`: **Introduction to Bakelite** &mdash; High-performance virtual filesystem and binary container engine for Crystal.
      #
      # ##### `B_ARCHITECTURE`
      # - `B_ARCHITECTURE::CHUNKING_AND_IO`: **Chunking and Streaming IO** &mdash; Architecture of bounded-memory streaming and random access IO.
      #
      # ##### `C_DSL`
      # - `C_DSL::MACROS_AND_VOLUMES`: **Compile-Time DSL and Volumes** &mdash; Using Bakelite macros to embed and organize assets in code.
      #
      # ##### `D_CONTAINERS`
      # - `D_CONTAINERS::BINARY_CONTAINERS`: **Binary Containers and CLI Toolchain** &mdash; Post-compile executable overlay and standalone archive manipulation.
      #
      def self.topic_03_table_of_contents : Nil; end

      # :nodoc:
      def self.quick_start : Nil
        topic_01_quick_start
      end

      # :nodoc:
      def self.reading_paths : Nil
        topic_02_reading_paths
      end

      # :nodoc:
      def self.table_of_contents : Nil
        topic_03_table_of_contents
      end
    end
  end

  require "./docs/a_overview/introduction"
  require "./docs/b_architecture/chunking_and_io"
  require "./docs/c_dsl/macros_and_volumes"
  require "./docs/d_containers/binary_containers"

  alias Docs = ::Bakelite::Docs
{% end %}
