# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
  module Bakelite
    module Docs
      module F_CONCURRENCY
        # # Concurrency and Thread Safety
        #
        # In modern games and web servers, multiple fibers or background OS threads frequently
        # query virtual assets concurrently. Bakelite provides robust concurrency protections
        # ensuring safe, race-free operation.
        #
        # ### Executive Summary & Key Topics
        #
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Topic</th>
        #       <th>Method / Anchor</th>
        #       <th>Description</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td><strong>Synchronized Container IO</strong></td>
        #       <td><code>.topic_01_synchronized_io</code></td>
        #       <td>Atomic seek-and-read protection for shared container file handles.</td>
        #     </tr>
        #     <tr>
        #       <td><strong>Multi-Fiber Parallel Execution</strong></td>
        #       <td><code>.topic_02_concurrent_fiber_reads</code></td>
        #       <td>Concurrency patterns verified by automated test suites.</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        module THREAD_SAFETY
          # **Synchronized Container IO**: Atomic seek-and-read protection for shared container file handles.
          #
          # When a `.bkl` container or executable overlay is mounted at runtime via `Container::Reader`,
          # the underlying container file is wrapped in `Bakelite::SynchronizedIO`.
          #
          # `SynchronizedIO` protects all file pointer seeking and chunk extraction through an internal
          # `Thread::Mutex`. When multiple concurrent fibers open different (or identical) files within
          # the container, each chunk read executes atomically via `read_at(offset, slice)`.
          #
          def self.topic_01_synchronized_io : Nil; end

          # **Multi-Fiber Parallel Execution**: Concurrency patterns verified by automated test suites.
          #
          # The Bakelite concurrency test suite (`spec/concurrency_spec.cr`) stress-tests 30
          # concurrent fibers simultaneously seeking and streaming from the same container:
          # - Fibers can seek to arbitrary positions simultaneously without corrupting neighbor streams.
          # - Each `FileIO` maintains its own independent sliding active chunk and position pointer.
          # - Clean resource release upon stream closure.
          #
          def self.topic_02_concurrent_fiber_reads : Nil; end
        end
      end
    end
  end
{% end %}
